version: '3'

services:

  bun:
    image: jarredsumner/bun:edge
    working_dir: "/usr/app"
    container_name: bun-app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - "./app:/usr/app"
    command: sh
