version: '3'

services:

  lan-https-server:
    image: nginx
    # restart: "unless-stopped"
    container_name: "nginx"
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./setting/etc:/etc/nginx"
      - "./setting/log:/var/log/nginx"
      - "./setting/root:/usr/share/nginx"
    working_dir: "/usr/share/nginx"
    command: 
      - sh
      - -c
      - |
        nginx -c /etc/nginx/nginx.conf
        nginx -s reload
        echo ok
        bash

#apt-get update -y
#apt install iputils-ping -y
#apt install net-tools -y