version: '3'

services:

  nodejs:
    image: "node:16-alpine"
    working_dir: "/usr/app"
    container_name: app
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - "./app:/usr/app"
    command: "node"
