version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpass
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: postgres-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: linyupark@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpass
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "15432:80"
    volumes:
      - ./admin:/var/lib/pgadmin
    links:
      - "db:pgsql-server"
